/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPriorityRouteImport } from './routes/_authenticated/priority'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedDataRouteImport } from './routes/_authenticated/data'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPriorityRoute = AuthenticatedPriorityRouteImport.update({
  id: '/_authenticated/priority',
  path: '/priority',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/_authenticated/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDataRoute = AuthenticatedDataRouteImport.update({
  id: '/_authenticated/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/data': typeof AuthenticatedDataRoute
  '/import': typeof AuthenticatedImportRoute
  '/priority': typeof AuthenticatedPriorityRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/data': typeof AuthenticatedDataRoute
  '/import': typeof AuthenticatedImportRoute
  '/priority': typeof AuthenticatedPriorityRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/data': typeof AuthenticatedDataRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/priority': typeof AuthenticatedPriorityRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/data' | '/import' | '/priority' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/data' | '/import' | '/priority' | '/'
  id:
    | '__root__'
    | '/_authenticated/data'
    | '/_authenticated/import'
    | '/_authenticated/priority'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedDataRoute: typeof AuthenticatedDataRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedPriorityRoute: typeof AuthenticatedPriorityRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/priority': {
      id: '/_authenticated/priority'
      path: '/priority'
      fullPath: '/priority'
      preLoaderRoute: typeof AuthenticatedPriorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/data': {
      id: '/_authenticated/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof AuthenticatedDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedDataRoute: AuthenticatedDataRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedPriorityRoute: AuthenticatedPriorityRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
